/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXPGAUSS
#define ROOEXPGAUSS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExpGauss : public RooAbsPdf {
public:
  RooExpGauss() {} ; 
  RooExpGauss(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha);
  RooExpGauss(const RooExpGauss& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpGauss(*this,newname); }
  inline virtual ~RooExpGauss() { }
  virtual Double_t analyticalIntegral( Int_t code, const char* rangeName=0 ) const;
protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  
  Double_t evaluate() const ;
  Double_t ApproxErf(Double_t arg) const ;
 
private:

  ClassDef(RooExpGauss,1) // Your description goes here...
};
 
#endif
